from exceptobject import process

try:
    print('Calling the process function')
    process()
except Exception as e:
    print(e)